global:
  resolve_timeout: 2m

route:
  receiver: 'email-notifications' # Change the receiver to the email configuration

receivers:
- name: 'email-notifications' # Define the email receiver
  email_configs:
    - to: 'aekems@gmail.com' # Replace with your email address
      from: 'ekemena.akpavie@alaralegal.com.ng' # Replace with the sender email address
      smarthost: 'smtppro.zoho.com:587' # Replace with your SMTP server address and port
      auth_username: 'aekems@gmail.com' # Replace with your SMTP username
      auth_password: 'Manunited7!' # Replace with your SMTP password
      send_resolved: true

- name: 'slack-notifications'
  slack_configs:
    - api_url: "https://hooks.slack.com/services/YOUR-SLACK-API-URL" # Replace with your Slack Incoming Webhook URL
      channel: '#general' # Replace with the Slack channel or user where you want to send notifications
      send_resolved: true # Set to true to send resolved alerts as well

